default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] ||= 'db' %>
  username: <%= ENV['POSTGRES_USER'] ||= 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ||= '' %>
  database: test

production:
  <<: *default
  database: bleater
  username: bleater
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
